{
 "title": "New dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Количество запросов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Потребление RAM",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Количество предсказаний цен",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    { "expr": "price_predictions_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Использование CPU",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "custom_cpu_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Длительность запроса",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Потребление диска",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "custom_memory_usage_percent", "legendFormat": "__auto" }
   ]
  }
 ]
}